server:
  port: 80

#Mysql数据库
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/linjunbin?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    #是否开启缓存，开发时可设置为 false ，默认为 true
  thymeleaf:
    cache: false
    #检查模板是否存在，默认为 true
    check-template: true
    #检查模板位置是否存在，默认为 true
    check-template-location: true
    #模板文件编码
    encoding: UTF-8
    #模板文件位置
    prefix: classpath:/templates/
    #Content Type 配置
    servlet:
      content-type: text/html
    #模板文件后缀
    suffix: .html
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  servlet:
    multipart:
      location: E:\student\Projects\English-Project\虚拟目录\

#spring集成Mybatis环境
mybatis:
  #pojo别名扫描包
  type-aliases-package: lin.jun.bin.model
  #加载Mybatis映射文件
  mapper-locations: classpath:mapper/*Mapper.xml


realPath: E:\student\Projects\English-Project\虚拟目录\