server:
  port: 80
  servlet:
    context-path: /lin

#Mysql数据库
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/linjunbin?useUnicode=true&characterEncoding=utf8
    username: root
    password: root

#spring集成Mybatis环境
mybatis:
  #pojo别名扫描包
  type-aliases-package: lin.jun.bin.model
  #加载Mybatis映射文件
  mapper-locations: classpath:mapper/*Mapper.xml